name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:

  #launch-tmate-shell:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: Setup tmate session
  #    uses: mxschmitt/action-tmate@v3

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          # install .codedoc dependencies
          cd .codedoc
          npm install
          # install codedoc
          npm install @codedoc/cli
          PATH=./.codedoc/node_modules/.bin:$PATH # only .codedoc/node_modules/.bin is the important part of path
          # build repo
          cd ..
          export NODE_OPTIONS=--openssl-legacy-provider
          codedoc build
          # copy assets
          cp favicon.ico dist/
          cp -r img/ dist/img/
          # mark no jekyll
          touch dist/.nojekyll
        env:
          GITHUB_BUILD: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
