name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        continue-on-error: true
        run: |
          # install codedoc
          cd .codedoc
          npm install @codedoc/cli
          # install .codedoc dependencies
          # (cd .codedoc && npm install)
        env:
          GITHUB_BUILD: true
        
      - name: Build
        # continue-on-error: true
        run: |
          # build repo
          (PATH=$(npm bin):$PATH && codedoc build)
        env:
          GITHUB_BUILD: true

      - name: Copy
        run: |
          # copy assets
          cp favicon.ico dist/
          cp -r img/ dist/img/
          # mark no jekyll
          touch dist/.nojekyll
        env:
          GITHUB_BUILD: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
